### ISSUE TITLE
Webpack integration?

### ISSUE THREAD

**Issue by sanchan** [stefanmaric/eslintblame#1]
First, I found this package really useful, thanks for your good job! :)

I want to know if it's possible to integrate this package into Webpack, so everytime that it compiles my assets, it blames. If it's possible, how can I get it working?

Thanks

**Comment by stefanmaric** [comment]
Hi @sanchan,

I'm not a hardcore user of webpack, but I think it should be possible.

Do you already run `eslint`/`snazzy` on your webpack build?
